set(ERROR_MESSAGE "Cannot find the TestU01 installation. Please set TESTU01_ROOT to the root directory containing TESTU01.")
mark_as_advanced( TESTU01_ROOT_DIR )
if(TESTU01_ROOT_DIR STREQUAL "")
	FIND_LIBRARY(TestU01 NAMES testu01 PATHS /usr/local/lib)
    FIND_LIBRARY(ProbDist NAMES probdist PATHS /usr/local/lib)
    FIND_LIBRARY(MyLib NAMES mylib PATHS /usr/local/lib)
    if(NOT TestU01)
        message(FATAL_ERROR "TestU01 library not found")
    endif()
    if(NOT ProbDist)
        message(FATAL_ERROR "ProbDist library not found")
    endif()
    if(NOT MyLib)
        message(FATAL_ERROR "MyLib library not found")
    endif()
    set(TESTU01_INCLUDE_DIRS /usr/local/include)
    set(TESTU01_LIBRARY_DIRS /usr/local/lib)
else()
    FIND_LIBRARY(TestU01 NAMES testu01 PATHS ${TESTU01_ROOT_DIR}/lib)
    FIND_LIBRARY(ProbDist NAMES probdist PATHS ${TESTU01_ROOT_DIR}/lib)
    FIND_LIBRARY(MyLib NAMES mylib PATHS ${TESTU01_ROOT_DIR}/lib)
    if(NOT TestU01)
        message(FATAL_ERROR "TestU01 library not found")
    endif()
    if(NOT ProbDist)
        message(FATAL_ERROR "ProbDist library not found")
    endif()
    if(NOT MyLib)
        message(FATAL_ERROR "MyLib library not found")
    endif()
    set(TESTU01_INCLUDE_DIRS ${TESTU01_ROOT_DIR}/include)
    set(TESTU01_LIBRARY_DIRS ${TESTU01_ROOT_DIR}/lib)
endif()

