// Copyright (c) 2022 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#include "../library/include/rocrand/rocrand_sobol64_precomputed.h"
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>

using namespace std;

template<typename DirectionVectorType>
void write_matrices(std::ofstream&       fout,
                    const std::string    name,
                    DirectionVectorType* directions,
                    int32_t              n,
                    int32_t              bits,
                    uint32_t             offset)
{
    fout << "static const ";
    fout << ((sizeof(DirectionVectorType) == 4) ? "unsigned int " : "unsigned long long int ");
    fout << name
         << ((sizeof(DirectionVectorType) == 4) ? "[SCRAMBLED_SOBOL32_N] = "
                                                : "[SCRAMBLED_SOBOL64_N] = ");
    fout << "{";
    fout << std::endl;
    fout << "    ";

    for(int k = 0; k < n; k++)
    {
        fout << "0x";
        fout << std::hex << std::setw(sizeof(DirectionVectorType) * 2) << std::setfill('0')
             << directions[k] + offset << ",";
        if((k + 1) % bits == 0 && k != (n - 1))
            fout << std::endl << "    ";
        else if(k != (n - 1))
            fout << " ";
    }
    fout << std::endl << std::endl;
    fout << "};" << std::endl;
}

int main(int argc, char const* argv[])
{
    if(argc != 2 || std::string(argv[1]) == "--help")
    {
        std::cout << "Usage:" << std::endl;
        std::cout << "  ./scrambled_sobol64_direction_vector_generator "
                     "../../library/include/rocrand/rocrand_scrambled_sobol64_precomputed.h"
                  << std::endl;
        return -1;
    }

    const std::string file_path(argv[1]);
    std::ofstream     fout(file_path, std::ios_base::out | std::ios_base::trunc);

    fout << R"(// Copyright (c) 2022 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef ROCRAND_SCRAMBLED_SOBOL64_PRECOMPUTED_H_
#define ROCRAND_SCRAMBLED_SOBOL64_PRECOMPUTED_H_

// Auto-generated file. Do not edit!
// Generated by tools/scrambled_sobol64_direction_vector_generator

)";

    fout << "#ifndef SCRAMBLED_SOBOL_DIM" << std::endl;
    fout << "    #define SCRAMBLED_SOBOL_DIM " << SOBOL_DIM << std::endl;
    fout << "#endif" << std::endl;
    fout << "#ifndef SCRAMBLED_SOBOL64_N" << std::endl;
    fout << "    #define SCRAMBLED_SOBOL64_N " << SOBOL64_N << std::endl;
    fout << "#endif" << std::endl;
    fout << std::endl;

    write_matrices(fout,
                   "h_scrambled_sobol64_direction_vectors",
                   h_sobol64_direction_vectors,
                   SOBOL64_N,
                   64,
                   1280000);

    fout << R"(
#endif // ROCRAND_SCRAMBLED_SOBOL64_PRECOMPUTED_H_
)";

    return 0;
}
