// Copyright (c) 2023 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#ifndef ROCRAND_TOOLS_UTILS_HPP_
#define ROCRAND_TOOLS_UTILS_HPP_

#include <filesystem>
#include <fstream>
#include <string_view>

namespace rocrand_tools
{

inline void write_asm_binary_embed(const std::filesystem::path output,
                                   const std::filesystem::path binary,
                                   const std::string_view      symbol)
{
    std::ofstream source_out(output, std::ios_base::out | std::ios_base::trunc);
    source_out << "#if defined(ROCRAND_EXECUTABLE_FORMAT_ELF)\n"
               << "    .section .note.GNU-stack,\"\",@progbits\n"
               << "    .type " << symbol << ",@object\n"
               << "    .section .rodata\n"
               << "#elif defined(ROCRAND_EXECUTABLE_FORMAT_PE_COFF)\n"
               << "    .section .rdata\n"
               << "#else\n"
               << "    #error \"Unknown object format\"\n"
               << "#endif // ROCRAND_EXECUTABLE_FORMAT\n"
               << "    .globl " << symbol << "\n"
               << "    .p2align 8\n"
               << symbol << ":\n"
               << "    .incbin \"" << binary << "\"\n";
}

inline std::ostream& write_preamble(std::ostream& os, std::string_view tool_name)
{
    os << R"(// Copyright (c) 2023 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Auto-generated file. Do not edit!
// Generated by tools/)"
       << tool_name << "\n"
       << '\n';

    return os;
}

} // namespace rocrand_tools

#endif // ROCRAND_TOOLS_UTILS_HPP_
