name: Check Clang-Format on Diff

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Check Clang-Format on Diff
      run: |
        chmod +x clang-format-diff.sh
        ./clang-format-diff.sh
